# Generated by Django 4.0.4 on 2022-05-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('PJ', 'Punjab'), ('SN', 'Sindh'), ('KP', 'Khyber Pakhtunkhwa'), ('BL', 'Balochistan')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_class', models.CharField(choices=[('9', 'Class-9'), ('10', 'Class-10'), ('11', 'Inter Part-I'), ('12', 'Inter Part-II')], default='9', max_length=2)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='questions.board')),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'unique_together': {('board', 'board_class')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, choices=[('URD', 'Urdu'), ('ENG', 'English'), ('ISL', 'Islamiyat'), ('PHY', 'Physics'), ('CHE', 'Chemistry'), ('BIO', 'Biology'), ('MTM', 'Mathematics'), ('CMP', 'Computer'), ('STA', 'Statistics')], default='MIS', max_length=3)),
                ('classes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='questions.class')),
            ],
            options={
                'unique_together': {('subject', 'classes')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100, unique=True, verbose_name='Unit Name')),
                ('unit_number', models.CharField(max_length=3, unique=True, verbose_name='Unit Number')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='questions.subject')),
            ],
        ),
    ]
