# Generated by Django 4.0.4 on 2022-05-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='subject',
            new_name='chapter',
        ),
    ]
