# Generated by Django 4.0.4 on 2022-05-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_subject_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='classes',
        ),
        migrations.AddField(
            model_name='subject',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='questions.class', verbose_name='Class'),
        ),
    ]
