# Generated by Django 4.0.4 on 2022-05-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_topic_board_topic_class_name_topic_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
