# Generated by Django 4.0.4 on 2022-05-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_subject_classes_subject_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.CharField(choices=[('1', 'UNIT-1'), ('2', 'UNIT-2'), ('3', 'UNIT-3'), ('4', 'UNIT-4'), ('5', 'UNIT-5'), ('6', 'UNIT-6'), ('7', 'UNIT-7'), ('8', 'UNIT-8'), ('9', 'UNIT-9'), ('10', 'UNIT-10'), ('11', 'UNIT-11'), ('12', 'UNIT-12'), ('13', 'UNIT-13'), ('14', 'UNIT-14'), ('15', 'UNIT-15'), ('16', 'UNIT-16'), ('17', 'UNIT-17'), ('18', 'UNIT-18'), ('19', 'UNIT-19'), ('20', 'UNIT-20'), ('21', 'UNIT-21'), ('22', 'UNIT-22'), ('23', 'UNIT-23'), ('24', 'UNIT-24'), ('25', 'UNIT-25'), ('26', 'UNIT-26'), ('27', 'UNIT-27'), ('28', 'UNIT-28'), ('29', 'UNIT-29'), ('30', 'UNIT-30')], max_length=3, verbose_name='Unit Number'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('subject', 'unit_number')},
        ),
    ]
