# Generated by Django 4.0.4 on 2022-05-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_topic_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
