# Generated by Django 4.0.4 on 2022-05-10 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_unit_unit_number_alter_unit_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='classes',
        ),
        migrations.CreateModel(
            name='SubjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.subject')),
                ('subject_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.class', verbose_name='Subject Class')),
            ],
        ),
    ]
