# Generated by Django 4.0.4 on 2022-05-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_subjectclass_options_alter_subject_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectclass',
            unique_together={('subject_class', 'subject')},
        ),
    ]
