# Generated by Django 4.0.4 on 2022-06-10 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_topic_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
                ('question', models.CharField(blank=True, max_length=600, null=True)),
                ('option1', models.CharField(blank=True, max_length=200, null=True)),
                ('option2', models.CharField(blank=True, max_length=200, null=True)),
                ('option3', models.CharField(blank=True, max_length=200, null=True)),
                ('option4', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.CharField(choices=[(1, 'Option1'), (2, 'Option2'), (3, 'Option3'), (4, 'Option4')], max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.chapter')),
            ],
        ),
    ]
