# Generated by Django 4.0.4 on 2022-05-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='course',
            new_name='unit',
        ),
    ]
