# Generated by Django 4.0.4 on 2022-05-10 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_rename_course_question_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='questions.subjectclass'),
        ),
    ]
