# Generated by Django 4.0.4 on 2022-06-10 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.board'),
        ),
        migrations.AddField(
            model_name='question',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.class'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.topic'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'MCQ'), (2, 'Short Question'), (3, 'Long Question')], null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
