# Generated by Django 4.0.4 on 2022-06-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_question_board_question_class_name_question_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Option1'), (2, 'Option2'), (3, 'Option3'), (4, 'Option4')], null=True),
        ),
    ]
