# Generated by Django 4.0.4 on 2022-06-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
