# Generated by Django 4.0.4 on 2022-05-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='unit',
            name='subject_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.subjectclass'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('subject_name', 'unit_number')},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='subject',
        ),
    ]
