# Generated by Django 4.0.4 on 2022-05-10 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_alter_unit_unique_together_unit_subject_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.class'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('unit_subject', 'unit_number')},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='subject_name',
        ),
    ]
