# Generated by Django 4.0.4 on 2022-05-11 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_alter_unit_unique_together_unit_unit_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
