# Generated by Django 4.0.4 on 2022-05-11 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_question_created_on_question_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['id'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='class',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.board'),
        ),
    ]
