# Generated by Django 4.0.4 on 2022-05-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_alter_board_options_alter_class_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='class',
            name='boards',
            field=models.ManyToManyField(blank=True, null=True, to='questions.board'),
        ),
        migrations.RemoveField(
            model_name='class',
            name='board',
        ),
    ]
