# Generated by Django 4.0.4 on 2022-05-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_alter_class_unique_together_class_boards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='boards',
            field=models.ManyToManyField(to='questions.board'),
        ),
    ]
