# Generated by Django 4.0.4 on 2022-05-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_alter_class_boards'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_subject',
        ),
    ]
