# Generated by Django 4.0.4 on 2022-05-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_alter_unit_unique_together_remove_unit_unit_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('unit_subject', 'unit_number')},
        ),
    ]
