# Generated by Django 4.0.4 on 2022-05-15 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_unit_unit_subject_alter_unit_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectclass',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subjectclass',
            name='subject_class',
        ),
        migrations.RemoveField(
            model_name='subjectclass',
            name='subject_name',
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_class',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_subject',
        ),
        migrations.RemoveField(
            model_name='class',
            name='board_class',
        ),
        migrations.RemoveField(
            model_name='class',
            name='boards',
        ),
        migrations.AddField(
            model_name='class',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.board'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_icon',
            field=models.ImageField(blank=True, upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_name',
            field=models.CharField(choices=[('9', 'Class-9'), ('10', 'Class-10'), ('11', 'Inter Part-I'), ('12', 'Inter Part-II')], db_column='class', default='9', max_length=2),
        ),
        migrations.AddField(
            model_name='class',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectClass',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
