# Generated by Django 4.0.4 on 2022-05-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_alter_subjectclass_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('board', 'class_name')},
        ),
    ]
