# Generated by Django 4.0.4 on 2022-05-15 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_alter_class_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_icon',
            new_name='icon',
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=30, unique=True)),
                ('total_type_questions', models.PositiveSmallIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('icon', models.ImageField(blank=True, upload_to='icons/')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.board')),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.class')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('subject', 'class_name')},
            },
        ),
    ]
