# Generated by Django 4.0.4 on 2022-05-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_rename_class_icon_class_icon_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
