# Generated by Django 4.0.4 on 2022-05-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(choices=[('9', 'Class-9'), ('10', 'Class-10'), ('11', 'Inter Part-I'), ('12', 'Inter Part-II')], db_column='class', max_length=2),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
