# Generated by Django 4.0.4 on 2022-05-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_alter_chapter_title_alter_class_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(choices=[(1, 'Class-9'), (2, 'Class-10'), (3, 'Inter Part-I'), (4, 'Inter Part-II')], db_column='class', max_length=2),
        ),
    ]
