# Generated by Django 4.0.4 on 2022-05-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_alter_class_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board',
            new_name='name',
        ),
    ]
