# Generated by Django 4.0.4 on 2022-05-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_rename_board_board_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Punjab'), (2, 'Sindh'), (3, 'Khyber Pakhtunkhwa'), (4, 'Balochistan')], max_length=1, unique=True),
        ),
    ]
