# Generated by Django 4.0.4 on 2022-05-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_alter_board_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Punjab'), (2, 'Sindh'), (3, 'Khyber Pakhtunkhwa'), (4, 'Balochistan')], unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Class-9'), (2, 'Class-10'), (3, 'Inter Part-I'), (4, 'Inter Part-II')], db_column='class'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='total_type_questions',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
