# Generated by Django 4.0.4 on 2022-05-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0031_alter_board_name_alter_class_class_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'class_name')},
        ),
    ]
