# Generated by Django 4.0.4 on 2022-05-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0032_rename_subject_subject_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('board', 'name')},
        ),
    ]
