"""
Django settings for brainbooks project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

from .common import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r!8y#@42hxw#wl(w*zuqqw3(e=x!1!ld$s+5s5z9j(b_39mf(g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


INSTALLED_APPS += [
    'django_extensions',
    'data_browser',
]

# django-debug-toolbar
# ------------------------------------------------------------------------------
# https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#prerequisites
INSTALLED_APPS += ["debug_toolbar"]  # noqa F405
# https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#middleware
MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware"]  # noqa F405
# https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html#debug-toolbar-config
DEBUG_TOOLBAR_CONFIG = {
    "DISABLE_PANELS": ["debug_toolbar.panels.redirects.RedirectsPanel"],
    "SHOW_TEMPLATE_CONTEXT": True,
}

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]


DATABASES = {
   'default': {
        'ENGINE': 'django.db.backends.mysql', #postgresql_psycopg2',
        'NAME': 'brainbooks',
        'USER': 'root',
        'PASSWORD': '',
        'OPTIONS': {'charset': 'utf8mb4',
                    "init_command": "SET foreign_key_checks = 0;",
                    'sql_mode': 'traditional',},

    }
}


"""
While in development, STATIC_ROOT does nothing. You don't even need to set it.
Django looks for static files inside each app's directory (myProject/appName/static) and serves them automatically.

This is the magic done by manage.py runserver when DEBUG=True
"""
STATIC_URL = 'static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') #Useless in development, no need to set it

# Extra places for collectstatic to find static files.
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Code for Jupyter notebook

# import os
# import django
# os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'brainbooks.settings')
# os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
# django.setup()

LOCAL_DEV = True



